### ISSUE TITLE
siamfc's acc is much lower!

### ISSUE THREAD

**Issue by aitaoquanyi** [huanglianghua/open-vot#1]
hi! 
    thanks for your nice work.but i find the IOU and prec is much lower.
![vot2017](https://user-images.githubusercontent.com/30489150/40289646-29809042-5cec-11e8-8586-1a90943ec62e.jpg)

**Comment by huanglianghua** [comment]
@aitaoquanyi Thanks for reporting the issue.

It is a logging bug in [lib/managers/manager_siamfc.py#L72](https://github.com/huanglianghua/open-vot/blob/master/lib/managers/manager_siamfc.py#L72) where it only records the last IoU and Prec. The original code is:

```
# logging
self.logger.add_text(tag, 'Overall Performance: IoU: {:.3f} Prec: {:.3f} Speed: {:.3f} fps'.format(
    mean_iou, prec, speed_fps), step)
self.logger.add_scalar(tag + '/iou_overall', mean_iou, step)
self.logger.add_scalar(tag + '/prec_overall', prec, step)
self.logger.add_scalar(tag + '/speed_overall', speed_fps, step)
```

It should have been:

```
self.logger.add_text(tag, 'Overall Performance: IoU: {:.3f} Prec: {:.3f} Speed: {:.3f} fps'.format(
    avg_iou, avg_prec, avg_speed), step)
self.logger.add_scalar(tag + '/iou_overall', avg_iou, step)
self.logger.add_scalar(tag + '/prec_overall', avg_prec, step)
self.logger.add_scalar(tag + '/speed_overall', avg_speed, step)
```

I will check and fix the bug. But you are free to directly change the logging code to get correct results.

**Comment by huanglianghua** [comment]
The logging bug has been fixed.

**Comment by aitaoquanyi** [comment]
@huanglianghua get it, thanks. the vot2017 mean_iou is same as the paper?

**Comment by huanglianghua** [comment]
@aitaoquanyi The mean_iou corresponds to the AO metric in vot2017 (not the EAO).

The Expected Average Overlap (EAO) performs re-initialization each time when a target is lost, which is not implemented yet.
