### ISSUE TITLE
BUG in trainer_siamfc.py

### ISSUE THREAD

**Issue by tcwtc** [huanglianghua/open-vot#11]
https://github.com/huanglianghua/open-vot/blob/847ba874af9275d2648ee1ab6465d49208f22269/lib/trainers/trainer_siamfc.py#L97

Should it be tracker.track(....)? Then how to set the init rect?

**Comment by huanglianghua** [comment]
@tianchenwang The `self.track` refers to the `track` member function defined in earlier version of `OpenVOT`, in `manager_siamfc.py`. However, in recent versions we renamed `manager_siamfc.py` to `trainer_siamfc.py` and removed the `track` function for clarity. Haven't tested yet however.

A newest version of SiamFC with training function and comparable training performance is under development and will be merged into OpenVOT in a short time. Thanks.
