### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by DL-85** [huanglianghua/open-vot#12]
I wonder why you put quick_example.py and run_tracking.py in the examples directory？Runing the scripts in examples directory raise the error "no module named 'lib'", while put them in the root directory (open-vot) working fine. 
Did I make some mistakes? Should the scripts be in examples directory or the root?

**Comment by huanglianghua** [comment]
@DL-85 The error differs with different computer systems. Some systems take the path of script file as `cwd` but others not. To keep the repo clear, we put all the examples files in the `examples` folder. But it's OK for you to directly copy the files in `examples` to the root directory.
