### ISSUE TITLE
Dead link for pretrained model

### ISSUE THREAD

**Issue by herleeyandi** [huanglianghua/open-vot#3]
Hello I can't download your pretrained model. Can you share it with a new link?
-Thank you-

**Comment by huanglianghua** [comment]
@herleeyandi Hi, I have checked the link and it works. Can you try again? Or, alternatively, you can directly download the pretrained models from the project page of each tracker, i.e., for siamfc: http://www.robots.ox.ac.uk/~luca/siamese-fc.html and for goturn: http://davheld.github.io/GOTURN/GOTURN.html.
