### ISSUE TITLE
[bug] isinstance('ABC', collections.Container) return true.

### ISSUE THREAD

**Issue by mayorx** [huanglianghua/open-vot#5]
https://github.com/huanglianghua/open-vot/blob/818356d0484138609489c28bb4e0b2a7f59703d7/lib/experiments/otb.py#L34

tracker_names is string ('SiamFC', for example).

```
        if not isinstance(tracker_names, collections.Container):
            tracker_names = [tracker_names]

        for name in tracker_names:
            ...
```

name will iterator 'SiamFC' as 'S' 'i' 'a' 'm' 'F' 'C'

**Comment by jensenzhoujh** [comment]
well, you can delete the 'not'

**Comment by huanglianghua** [comment]
The issue has been fixed.
